services:

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "sleep 30 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - elasticsearch
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false


    ports:
      - 9200:9200

volumes:
  pg_data: