# Generated by Django 5.1.4 on 2024-12-28 09:52

import django.contrib.postgres.fields
from django.db import migrations, models

from config import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Рубрики статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления статьи')),
                ('owner', models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='автор рассылки', blank=True, null=True, on_delete=models.SET_NULL))
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['created_date'],
            },
        ),
    ]
